### ISSUE TITLE
Just pushed a commit (3be70b051025327db5d5f54cd5a1f777dea75943) that I think should enable this now (not on NPM yet). I wasn't familiar with memory mapped files before working on this change, but from my little testing it seems like you should be able to replicate this C# logic with memoryjs now. Updated the README with an example ([documentation](https://github.com/Rob--/memoryjs#memory-mapped-files-1)).

### ISSUE THREAD

**Issue by staceywhitmore-inl** [Rob--/memoryjs#108]
Just pushed a commit (3be70b051025327db5d5f54cd5a1f777dea75943) that I think should enable this now (not on NPM yet). I wasn't familiar with memory mapped files before working on this change, but from my little testing it seems like you should be able to replicate this C# logic with memoryjs now. Updated the README with an example ([documentation](https://github.com/Rob--/memoryjs#memory-mapped-files-1)).

To achieve what you want, this should work:
```javascript
const processObject = memoryjs.openProcess("example.exe");
const fileHandle = memoryjs.openFileMapping("MappedFooFile");

const baseAddress = memoryjs.mapViewOfFile(processObject.handle, fileHandle.handle, 0, 8, memoryjs.PAGE_READONLY);
const ask = memoryjs.readMemory(processObject.handle, baseAddress, memoryjs.DOUBLE);
```

This will map the first 8 bytes (size of double) of the memory mapped file to your target process memory and return the address. You just need to read the double at this address now to get the ASK value.

_Originally posted by @Rob-- in https://github.com/Rob--/memoryjs/issues/101#issuecomment-1318070180_

**Comment by staceywhitmore-inl** [comment]
When I try this I receive the following error: 
_**TypeError: memoryjs.openFileMapping is not a function**_
When I looked the src code in node_modules I couldn't find any occurrence of the method _openFileMapping()_. 
Am I missing a step?

**Comment by Rob--** [comment]
This change is not yet published to NPM. If you need this functionality, you can pull this repository directly. I'll publish it to NPM soon.

**Comment by staceywhitmore-inl** [comment]
Awesome! I'll give it try! Thanks for your quick reply. I think I currently have it installed via npm. So, I will need to uninstall the npm package, and then git clone or pull this repo, build from scratch and merge it with the sample code I'm trying out, correct? (Or, I could just clone this most recent push directly into my _node_modules_ directly in lieu of the _memoryjs_ directory currently there [and erasing it from my _packages.json_], no?) 
Sorry, I've always used npm so I wanted to make sure I was doing this correctly. 

Then I should be able to start up my C++ executable, which calls `CreateFileMapping() `and passes in a string/handel for the mapped item name I will access from my .js sample code, correct? And should the string I pass to` .openProcess() `be the name of my C++ executable I've started in a separate directory (which should be visible to my script as a running process)?
