### ISSUE TITLE
Feature: Open process using th32ProcessID instead of process name(multiple processes same name)

### ISSUE THREAD

**Issue by tigohenryschultz** [Rob--/memoryjs#116]
I would like to open multiple processes with the same name but do not see any methods to accomplish this.

Thanks

**Comment by prevzzy** [comment]
you can already do this, just pass PID instead of process name to openProcess function.

https://github.com/Rob--/memoryjs/commit/e8ec257c95b44546c56f76c12dc78298cd4eaf07

**Comment by Rob--** [comment]
Thanks @prevzzy
