### ISSUE TITLE
Unable to read String / Text

### ISSUE THREAD

**Issue by Glutch** [Rob--/memoryjs#12]
I've got a bunch of addresses from cheat engine. I can read ints just fine
`memoryjs.readMemory(0xCA11F4, memoryjs.INT)`
But i have never been able to read a string. memoryjs.STRING memoryjs.STR
Is this a bug?

Doing this async and printing the error gives nothing either

Using node version 6~

**Update after trying some more stuff**
Installed node version 6.9.1 32bit according to the instructions, since my application i want to read is 32bit. with nvm
npm run build32 inside project/node_modules/memoryjs

Now im getting this error
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
```

My application is surely 32bit. As seen in task manager -> details -> platform

Help would be greatly appreciated, memoryjs seems awesome.

**Comment by tuefekci** [comment]
had the same problem https://github.com/Rob--/memoryjs/issues/8

**Comment by Rob--** [comment]
@Glutch I've just experimented with strings, I will push an update soon that lets you write strings. I have not tested reading strings yet.

Are you still struggling with the build issue?

**Comment by Rob--** [comment]
Updated the library, hopefully should fix the string problems now. ([#ea44f09](https://github.com/Rob--/memoryjs/commit/ea44f09847d43937e9aaed2c348e9c5cb7e4424a))
