### ISSUE TITLE
Invalid data from readMemory

### ISSUE THREAD

**Issue by Chank1e** [Rob--/memoryjs#15]
Hey. I'm trying to readMemory from address, which I've select from CheatEngine. In CE I see value 101, but shen I try to read this in JS I get 3.
What problems can i have?

P.S. Trying to access cs 1.6 data)

**Comment by AxDSan** [comment]
I have the same issue, I think it's gotta be with the library, I have tried getting in contact with the author or the library #16 and I also have issues reading from memory, I'm pretty sure it's got to be with the library.

**Comment by AxDSan** [comment]
Digging up a little further, I think the `3` that we get it's an error code...
```js
const processObject = memoryjs.openProcess(processName);
console.log(JSON.stringify(processObject, null, 3));

var addr = 0x7ff662ff8f70;

/// <summary> Getting ready to read the memory.
/// <err> error message (empty if there were no errors). </err>
/// <value> the value stored at the given address in memory. </value>
/// <see>Documentation at: https://github.com/Rob--/memoryjs#readmemoryaddress-datatype-callback</see>
/// </summary>
memoryjs.readMemory(addr, 'int', (err, value)=> {
  if (err === "") {
    console.log(value);
  }else{
    console.log("ERROR:", err);
  }
});
```

So when error message is empty it means that everything was OK, but if error is NOT empty, then it means something went wrong.

**Comment by Chank1e** [comment]
Ye, but why sometimes it's invalid value?
I tried to find error in C++ code, but didn't find.

Do you think that we only need ptr function to get valid data?

P.S. I think, that author will never continue memoryjs. Need to fork and try to find an error.

**Comment by AxDSan** [comment]
Don't really know, but as recently as yesterday he commented on my issue, and he mentioned he could add a helper function to make the pointers addresses part to work, so that gets me to think that probably he is motivated to work on the issues, he also have expressed he is not a really well experienced C++ developer, and to be honest, me neither, in fact I was having a little bit of trouble on how to properly read and general usage of the library.

**Comment by Chank1e** [comment]
Oh, that's pretty cool.
I'm just learning C++ in university, so my knowledge is like "How to read file of numbers and do quicksort of them". But, as for me, possibility of reading memory in js is really cool. 

Would be great if community will help Robert to do that work)

**Comment by AxDSan** [comment]
> Hey guys, I am interested on improving this library and adding a few features. After my exams are over I've got a busy summer so I can't promise anything, but I will try to find time to address some issues and also review the current PRs.

Awesome! 💃

**Comment by cireu** [comment]
according to the docs， readMemory method expected at least 3 args but you just passed 2

**Comment by Wawy123** [comment]
You will also get wrong memory value if u forget to add ".exe" to process name

**Comment by p410n3** [comment]
> You will also get wrong memory value if u forget to add ".exe" to process name

Well of course, you can attach to other modules as well. Technically
