### ISSUE TITLE
how to specify a pointer?

### ISSUE THREAD

**Issue by AxDSan** [Rob--/memoryjs#16]
I need to read a pointer from memory, and there is nothing available to specify the address is a pointer

for example, in Frida, I would do something like
 
`var mem = Memory.readFloat(ptr(addr));`

but I don't seem to have `ptr()` available in this library.

**Comment by Rob--** [comment]
```js
const pointer = memoryjs.readMemory(address, 'dword');
const value = memoryjs.readMemory(pointer, 'float');
```

I could add a sort of helper method for sure, but all it would be doing is what I am doing in the snippet above?

**Comment by AxDSan** [comment]
either the library it's having troubles in the reading process or I'm doing something wrong, because the resulting value from `memoryjs` definitely is not the same from CE.

![](https://i.imgur.com/u3c6wSG.png)

**Comment by AxDSan** [comment]
#396285035

**Comment by AxDSan** [comment]
#issuecomment-396285035

**Comment by Wawy123** [comment]
I was also wondering if there is a way to read a pointer?

The snipper you provided doesnt seem to work :/ 

Any other ideas?

**Comment by Wawy123** [comment]
Never mind i found the soultion!

i just had to read pointer adress : const pointer = memoryjs.readMemory(address, 'dword');

and then add offset to this adress like: const value = memoryjs.readMemory(pointer+offset, 'float');
to get the value!

Thanks to @Rob-- for snippet :)

**Comment by Rob--** [comment]
If you are still struggling with this issue let me know, the library has a `intptr_t` data type (`memoryjs.PTR` or `memoryjs.POINTER`) which you can read and then read again into the data type of your choice.
