### ISSUE TITLE
Open Process by ID & Multi Process support.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Rob--/memoryjs#19]
Just a feature request, 
Can we open a process by id, specifying it by detecting if the argument is a string or int?

Rather than ```Process process``` could the library store the handle for re-use and support multiple processes?

A js object could be returned exposing methods which use that process handle, or similar to how SetTimeout works in js that you get a number you can put in to the functions as an arg.
Handle can just be passed as is as if it were an unsigned integer or by using a map of PID to handle.

I know I have done this in the past with node-ffi but a native module seems nicer to use.

Any thoughts?

**Comment by Rob--** [comment]
Multi-process support makes sense, not sure why I didn't incorporate it in the beginning. I will also look into opening a process by ID.

**Comment by Rob--** [comment]
Added multi-process support, I made it a breaking change. Some functions now require you to pass the handle of the process through (reading/writing memory and pattern scanning). Ideally in the future I will create a wrapper around the existing functions so you can create "instances" of the library specific to applications:

```
const csgo = memoryjs.newInstance("csgo.exe");
csgo.readMemory(address, dataType);
```

**Comment by LiamKarlMitchell** [comment]
Great thanks @Rob--
