### ISSUE TITLE
Read/Write buffer.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Rob--/memoryjs#20]
It should also be possible to read/write a buffer which can be used to read say, an objects struct from memory at once then parse through it in js.

Maybe something like this?
```js
process.read(buf, address, callback)
```

```
// Writing buffer, can get like this.
size_t packetLen = Buffer::Length(args[1]);
char* packet = Buffer::Data(args[1]);	

// Reading buffer.
char * buffer = new char[size];
ReadProcessMemory(hProcess, (LPVOID)dwAddress, &buffer, size, NULL);
info.GetReturnValue().Set(Nan::NewBuffer(buffer, size).ToLocalChecked());
```

Maybe this would be helpful?
https://community.risingstack.com/using-buffers-node-js-c-plus-plus/

https://github.com/Zysen/node-winprocess/blob/master/winprocess.cc#L229-L240

**Comment by LiamKarlMitchell** [comment]
I'm happy to implement this should I need it, will see how I go.

**Comment by PostCrafter** [comment]
Do I understand it correctly that this would allow me to read/write generic structs from and to memory just like the vector types?
If this is the case I would very much like to see this in a future version, as it's exactly what I'm gonna need for a project of mine.

**Comment by p410n3** [comment]
Yes. I think he already did it if I understood his email correctly.

**Comment by LiamKarlMitchell** [comment]
You could yes.

I've used concentrate and dissolve modules for a project in the past.
https://github.com/deoxxa/concentrate

**Comment by Rob--** [comment]
v.3.1.0: reading/writing of buffers added in bfa4cc71df216f7b6ddab9adfaae34c37fee1e7d

For information about writing or reading structures, refer to the [generic structures](https://github.com/Rob--/memoryjs#generic-structures) section of the readme.

Functions added:
[`readBuffer(handle, address, size[, callback])`](https://github.com/Rob--/memoryjs#readbufferhandle-address-size-callback)
[`writeBuffer(handle, address, buffer)`](https://github.com/Rob--/memoryjs#writebufferhandle-address-buffer)

@LiamKarlMitchell I've added a buffer read/write example [here](https://github.com/Rob--/memoryjs/blob/master/examples/buffers.js). Hopefully this is what you and @PostCrafter were looking for!

If you're happy to share your script here I'm sure others would find it useful :)

**Comment by LiamKarlMitchell** [comment]
Great stuff thanks @Rob--
