### ISSUE TITLE
Get & Set memory permissions.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Rob--/memoryjs#21]
If you want to write .code sections of memory you need to set the memory protections.
And possibly a flush instruction cache.

A way I have done this in the past is to make a SetProtection method.
```cpp
DWORD SetProtection(void* m_address, DWORD m_size, DWORD protection = PAGE_EXECUTE_READWRITE);

DWORD SetProtection(void* m_address, DWORD m_size, DWORD protection) 
{
	DWORD dwOldProtect;
	VirtualProtect(m_address, m_size, protection, &dwOldProtect);
	return dwOldProtect;
}
```

Then you can call it prior to writing over some memory, storing the return value, then use that return value to return the memory protections back to how they were.
```
void MemCpyProtected(void* m_address, const void* bytes, DWORD size)
{
	DWORD d = SetProtection(m_address, size);
	memcpy(m_address, bytes, size);
	SetProtection(m_address, size, d);
}
```

**Comment by Rob--** [comment]
Merged, thanks for your contribution, I'll play around with this before I push to NPM.
