### ISSUE TITLE
writeMemory with 8 bytes

### ISSUE THREAD

**Issue by Kraysh** [Rob--/memoryjs#26]
I need writeMemory with value 144 (NOP) in address 0x74542B with 8 bytes of size in GTA San Andreas.

I trying use long datatype to this but it does not happen as expected.
`memoryjs.writeMemory(processObject.handle, 0x74542B, 144, 'long')`

What is the right datatype or how do I make size be 8 bytes??

**Comment by p410n3** [comment]
Did you try 

    memoryjs.DOUBLE

?

**Comment by Rob--** [comment]
Long = 4 bytes
Double = 8 bytes
