### ISSUE TITLE
I am new to this.

### ISSUE THREAD

**Issue by Wawy123** [Rob--/memoryjs#27]
Hello!

As the title says im new to this and i have an issue.

I would like to ask how do i get the address of the specific value in the memory?

**Comment by Wawy123** [comment]
for example in cheat engine i got a value and i would like to read the address i got in cheat engine with memoryjs

**Comment by Wawy123** [comment]
Nevermind i found the soultion :)

**Comment by Wawy123** [comment]
it read the wrong value because i didnt add .exe to the end of the process name

**Comment by p410n3** [comment]
We all start somewhere. Keep it up!

**Comment by Wawy123** [comment]
It works great for now. Also the issue i noteced was if i add callback to writeMemory i get error that it requires 4 arguments.

**Comment by MelerEcckmanLawler** [comment]
Could you please post your code? I'm trying the same thing but it won't work.  I expected it to be simple since it's just a notepad window with the text `Hello World!` but the pattern scan function won't find it.
