### ISSUE TITLE
When i try to get modules it returns wrong information or if i build it as 32 bit it won't run-error 

### ISSUE THREAD

**Issue by Wawy123** [Rob--/memoryjs#30]
So i tried getting modules with no success.

If i get "hl2.exe" (cs:s) and i try to get modules with its th32ProcessID i get wrong modules (i need client.dll):
```
[ { modBaseAddr: 4194304,
    modBaseSize: 114688,
    szExePath: 'C:\\Games\\Counter-Strike Source\\hl2.exe',
    szModule: 'hl2.exe',
    th32ModuleID: 9764 },
  { modBaseAddr: 140734740627456,
    modBaseSize: 1970176,
    szExePath: 'C:\\Windows\\SYSTEM32\\ntdll.dll',
    szModule: 'ntdll.dll',
    th32ModuleID: 9764 },
  { modBaseAddr: 2009464832,
    modBaseSize: 335872,
    szExePath: 'C:\\Windows\\System32\\wow64.dll',
    szModule: 'wow64.dll',
    th32ModuleID: 9764 },
  { modBaseAddr: 2009923584,
    modBaseSize: 491520,
    szExePath: 'C:\\Windows\\System32\\wow64win.dll',
    szModule: 'wow64win.dll',
    th32ModuleID: 9764 },
  { modBaseAddr: 2009858048,
    modBaseSize: 40960,
    szExePath: 'C:\\Windows\\System32\\wow64cpu.dll',
    szModule: 'wow64cpu.dll',
    th32ModuleID: 9764 } ]
```

I also tried running ```npm run build32``` in memoryjs root but it crashes if i try to run it:

```
\node_modules\memoryjs\build\Release\memoryjs.node is not a valid Win32 application.
```

**Comment by p410n3** [comment]
Have you installed all the needed tools to start Compiling? Python and VC build tools are needed. Refer to the documentation. Building works fine for me

**Comment by Rob--** [comment]
Is your Node version 32 bit or 64 bit? And is hl2.exe 32 bit or 64 bit?

**Comment by Wawy123** [comment]
@p410n3 I made bhop for it so no need to fix this for now :)

Also @Rob--  my node is 64 bit hl2 is 32 bit i belive. I will try to solve it on my own and inform you about it if i fixed it

**Comment by p410n3** [comment]
Well node has to be x86 innit?

**Comment by p410n3** [comment]
> Also a question on how to read pointers.

Thats off topic and does not belong in this Repository. 

For now: you need to make multiple scans and compare them.

https://www.unknowncheats.me/forum/programming-for-beginners/110375-cheat-engine-finding-base-address-pointer-scan.html

But please stop being OT now

**Comment by Wawy123** [comment]
Ok i will stay on topic now.

**Comment by Rob--** [comment]
@Wawy123 Just pushed v3.0.2 to NPM. It would be much appreciated if you could see if it displays all the modules now.

**Comment by Wawy123** [comment]
Ok i will take a look

**Comment by Wawy123** [comment]
So as far as i know cs:s is 32 bit and if i try to run: npm run build32 it builds it.

But when i try to run my app i get the error: ```\node_modules\memoryjs\build\Release\memoryjs.node is not a valid Win32 application.```  It may be just an issue on my side. i will try to install 32 bit node.js now if that will help.

**Comment by Wawy123** [comment]
It works now!

Good job @Rob-- 🥇

**Comment by Rob--** [comment]
Np, enjoy! :)
