### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by WelaurS** [Rob--/memoryjs#37]
Hi. I trying to install memoryjs with `npm install Rob--/memory's` and getting error

`
c:\users\sergey\desktop\offset-dumper\node_modules\memoryjs\lib\functions.h(39): error C2039: call: not a member "functions" (file: ..\lib\functions.cc) [C:\Users\Sergey\Desktop\offset-dumper\node_module
s\memoryjs\build\memoryjs.vcxproj]
`

There is no problem when installing from npm, only from GitHub.

**Comment by albmar** [comment]
Well just have a look at [functions.h@39](https://github.com/Rob--/memoryjs/blob/abc9ee0066cb72e26c51a51e91572cc099d3dbab/lib/functions.h#L39). Using the scope operator onto the definition of the call function leads to searching for a call declaration inside the namespace _functions_, which doesn't exist yet. So either _functions::_ in front of the definition has to be removed or a declaration has to be added before the definition.

**Comment by Zephyr6** [comment]
I'm getting this same issue.

When installing this module from npm, it doesn't contain the callFunction method. This looks to be an issue relating to this method.

**Comment by WelaurS** [comment]
@Rob--, can you fix it, please? Or someone can do pull request?

**Comment by Rob--** [comment]
@WelaurS will look into this really soon! Sorry for the inconvenience! @Zephyr6 @albmar

**Comment by WelaurS** [comment]
@Rob-- ?

**Comment by p410n3** [comment]
What error

**Comment by eseapause** [comment]
Having the same exact issue, did anyone else find a solution? @WelaurS @Zephyr6

**Comment by Zephyr6** [comment]
It works fine if you clone the repo and use it that way instead of using the published package. 

I may be wrong, but the fix for this issue would be to simply publish a new version of this package.

**Comment by eseapause** [comment]
@Zephyr6 Republishing didn't work. Any other ideas?

**Comment by Rob--** [comment]
@eseapause Zephyr is saying that the published version of this package is currently broken, but the version that this repo contains is working. He is suggesting that you use this GitHub version and not the NPM version.

**Comment by Zephyr6** [comment]
Exactly correct. Just to clarify, the published version of this package works fine with the exception of the callFunction method. 

The easiest way to get around this is to uninstall the npm package and clone this repo and build it yourself. I've done this and it works fine (from what I can tell).

**Comment by eseapause** [comment]
@Zephyr6 @Rob-- Actually, my problem is a bit different. I'm not having any issues with the published version, but when I try to build this module myself via. the GitHub repo I get this error:
`c:\users\ryan\desktop\memoryjs\lib\functions.h(39): error C2039: 'call': is not a member of 'functions' (compiling sour
ce file ..\lib\functions.cc) [C:\Users\Ryan\Desktop\memoryjs\build\memoryjs.vcxproj]`

**Comment by Rob--** [comment]
That’s weird because I can build it perfect fine. When I get home I’ll publish the GitHub version to NPM and then you can directly install it from there and see if it fixes the issue. Sorry for the inconvenience!

**Comment by eseapause** [comment]
> That’s weird because I can build it perfectly fine. When I get home I’ll publish the GitHub version to NPM and then you can directly install it from there and see if it fixes the issue. Sorry for the inconvenience!

No problem. I'll try to build it on my Windows VPS and see if it works there as well.

**Comment by Rob--** [comment]
@eseapause just published v3.2.2. Also did a clean install in a folder and it was able to build fine. Remove `memoryjs` and try doing `npm install memoryjs` again! Let me know how it goes :)

**Comment by eseapause** [comment]
> @eseapause just published v3.2.2. Also did a clean install in a folder and it was able to build fine. Remove `memoryjs` and try doing `npm install memoryjs` again! Let me know how it goes :)

Now I am getting the issue with the published version. Last version was fine.

**Comment by Rob--** [comment]
Hmm that's really weird. If you create a new folder and try installing it there can you paste the error you get?

Also, unsure how NPM cache works but it may be worth trying `npm cache clean --force` and then `npm cache verify`?

**Comment by eseapause** [comment]
> Hmm that's really weird. If you create a new folder and try installing it there can you paste the error you get?
> 
> Also, unsure how NPM cache works but it may be worth trying `npm cache clean --force` and then `npm cache verify`?

Cleared cache, still have the issue.
https://pastebin.com/RWLV8PVt

**Comment by eseapause** [comment]
Here's something odd, the working version doesn't have a functions.h file, whilst the non-working version does.

**Comment by Rob--** [comment]
@eseapause nah that `Type` enum is in reference to the data types that are compatible with the external function call functionality.

What happens if you try this?
1. Do a clean install of `memoryjs`
2. Go to line 39 of `functions.h`
3. Change `Call functions::call` to `Call call`
4. Run `npm run build32`

Does this solve it or nah?

**Comment by eseapause** [comment]
> @eseapause nah that `Type` enum is in reference to the data types that are compatible with the external function call functionality.
> 
> What happens if you try this?
> 
> 1. Do a clean install of `memoryjs`
> 2. Go to line 39 of `functions.h`
> 3. Change `Call functions::call` to `Call call`
> 4. Run `npm run build32`
> 
> Does this solve it or nah?

Fixed. This is weird as hell.

**Comment by Rob--** [comment]
It's weird that it's not giving me build issues, either way I'll remove the `functions::` prefix as @albmar suggests and push/publish that. Sorry again this took so long! Thanks everyone.

**Comment by eseapause** [comment]
> It's weird that it's not giving me build issues, either way I'll remove the `functions::` prefix as @albmar suggests and push/publish that. Sorry again this took so long! Thanks everyone.

Let me know when it's pushed to npm, nodejs is getting mad that the node version used to compile is 64, but requires version 69  (nice).

**Comment by Rob--** [comment]
@eseapause published a new version to NPM including the fix I mentioned earlier. If it helps I'm using the latest version of NPM and v8.11.3 for NodeJS.

**Comment by eseapause** [comment]
This installation error was resolved, perhaps you want to close this issue?
Also, @Rob-- can you DM me on Discord - I have a further question that's unrelated to this. SportProgrammer#7588

**Comment by Rob--** [comment]
Awesome. And sure thing, just added you.
