### ISSUE TITLE
Pattern scanning

### ISSUE THREAD

**Issue by Pupix** [Rob--/memoryjs#4]
Hello!

I've found your project on `npm` and I think it's the only memory editing module for node in there. Seen that your last update was 7 months ago.

Are you still working on this or is it dead?

Are you still planning on adding the `pattern scanning` feature from your TODO list?

Cheers,
Pupix

**Comment by Rob--** [comment]
Hi,

I think so too! That's exactly why I made it in the first place! I couldn't find a library that allows reading or writing to memory. It's pretty much dead, I haven't intended on updating it as I no longer develop the program that used this library as a dependency but I may look into updating it to work with the latest version of Node.

I was also never even able to get pattern scanning to work in C++ but if I find time I'm sure I'll be able to get it working. From looking at your profile, I presume you intend to use this library with League of Legends in some way? :wink:

Regards,
Rob

**Comment by Pupix** [comment]
Yes, you got me.

I intend to create some dev tools that interact with the game's memory in real-time.

**Comment by Rob--** [comment]
Alright, I am planning to look into updating this library and will then possibly add pattern scanning when I do. However for the time being I have no idea when I will do this. In the meantime, feel free to submit a pull request!

Also I don't play League, are you allowed to do that?

**Comment by Pupix** [comment]
Glad to hear that.
Ofc it's not allowed, nobody allows you to edit their game's memory because you could break your/other players stuff.

That being said, what I plan to build is just to allow me fiddle with the game's environment in so called `custom games` where you can play all by yourself and not disrupt other player's game. Things like camera position, texture swapping ecc.

**Comment by Rob--** [comment]
Added the pattern scanning function, I've not tested this extensively and I've only tested it so far with CS:GO and it seems to be working perfectly. Hopefully you get the chance to try it out and report if it works or not.

**Comment by Pupix** [comment]
Thanks! I will give it a try and let you know if there's any issues.
