### ISSUE TITLE
Add "byte" type to WriteMemory.

### ISSUE THREAD

**Issue by eseapause** [Rob--/memoryjs#40]
Could you by chance just add a byte type to write/read memory and do all the buffer handling behind the scenes? Been having tons of trouble.

**Comment by Rob--** [comment]
I can add a byte type for sure. In regards to buffer handling, the closest I can do to handling it behind the scenes is iterating over the keys and values of an object to automatically construct the buffer but this might be difficult to do so because I'd have to predict types and assume order is correct, etc.

If you could provide some sample code I can try assisting you. Have you also checked out the [buffer example](https://github.com/Rob--/memoryjs/blob/master/examples/buffers.js)?

**Comment by eseapause** [comment]
I have, what I really need to write is multiple unalligned unsigned characters - I don't really know what I am looking for. Look at this thread: https://www.unknowncheats.me/forum/counterstrike-global-offensive/328613-external-chams.html (yes, I am using this for game hacking - nothing commercial though, just personal use and fun)

**Comment by Rob--** [comment]
@eseapause added "unsigned char" (alias "byte") in 9a16886c9179424b8f4047e178428af9411dcf43. Let me know if this works and then I'll update the repo properly and push to NPM.

**Comment by eseapause** [comment]
` this.memoryjs.memoryjs.writeMemory(this.memoryjs.handle, Enemy + this.offsets['netvars']['m_clrRender'], 255, "byte");` is resulting in "unexpected data type" from index.js:113 (memoryjs). Did I do something wrong? I cloned the github repository and replaced my files, I even checked that the index.js did indeed include 'byte' now.

**Comment by Rob--** [comment]
In the module directory, run `npm run build32` or `npm run build64` depending on your target architecture.

**Comment by eseapause** [comment]
> In the module directory, run `npm run build32` or `npm run build64` depending on your target architecture.

`npm ERR! missing script: build32`
I haven't ever grabbed a module from github, please excuse my lack of knowledge.

**Comment by Rob--** [comment]
Ah this was a compilation problem mentioned by another user a while ago. Should be an easy fix but I'm going to be away for the next few hours! If you want to fix it yourself in the meantime take a look at [this](https://github.com/Rob--/memoryjs/issues/37) issue!

**Comment by eseapause** [comment]
> Ah this was a compilation problem mentioned by another user a while ago. Should be an easy fix but I'm going to be away for the next few hours! If you want to fix it yourself in the meantime take a look at [this](https://github.com/Rob--/memoryjs/issues/37) issue!

Sounds good. Let me know when you're back. 👍

**Comment by Rob--** [comment]
Added the `byte` type in 9a16886c9179424b8f4047e178428af9411dcf43.
