### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Azperin** [Rob--/memoryjs#41]
Could you please add some more simple examples. Like how to find numbers address in 'calc.exe'.

```javascript
const memoryjs = require('memoryjs');
const processName = "calc.exe";
/*
	And then what ? How to find '5' in process ? How to get adress of this value and change it ?
*/
```

**Comment by JVictorV** [comment]
You should look up some reverse engineering examples about that, its not 100% related to the package

**Comment by Rob--** [comment]
I agree with @JVictorV. I can add scanning functionality if people want that, but it would be so much easier to just work with a proper tool such as Cheat Engine to find the address you want.

**Comment by Azperin** [comment]
Most anti-cheats are pissedoff when i launch CE ) And i heard if i will try to get adress with it in VACprotected game i'll be banned.

**Comment by Rob--** [comment]
Right click on the game in your Steam library and click properties, and for launch options type `-insecure +sv_lan 1`. This should disable VAC and launch it without an internet connection. Not sure how many games this works for, but I know it works for CS:GO.

**Comment by JohnDeved** [comment]
Wouldn't most anticheats probably get pissed of if you launch memory.js too?
Most anticheats easily detect memory access of simple programs

**Comment by Rob--** [comment]
Yeah most ACs easily detect open handles and RPM/WPM. I’m not sure if VAC has changed recently, but VAC used to not care about any of that and you could access the process and do whatever you wanted to do.

**Comment by JVictorV** [comment]
Well, most of the new anticheats have some serious detections and you will probably need to reverse them to understand what are they doing and how they detect you. You can always check some big gamehacking forums to get some information, but you will (probably) have to write some C++/ASM code to bypass all that stuff
