### ISSUE TITLE
Can not install memoryjs on ubuntu

### ISSUE THREAD

**Issue by akshayapadmanabhan** [Rob--/memoryjs#43]
make: Entering directory '/media/akshaya/New Volume/ctonode/node_modules/memoryjs/build'
  CXX(target) Release/obj.target/memoryjs/lib/memoryjs.o
../lib/memoryjs.cc:3:21: fatal error: windows.h: No such file or directory
 #include <windows.h>
                     ^
compilation terminated.
memoryjs.target.mk:103: recipe for target 'Release/obj.target/memoryjs/lib/memoryjs.o' failed
make: *** [Release/obj.target/memoryjs/lib/memoryjs.o] Error 1
make: Leaving directory '/media/akshaya/New Volume/ctonode/node_modules/memoryjs/build'

**Comment by p410n3** [comment]
As included in the error message:
    #include <windows.h>

This package uses the **WinAPI** on **Windows** to read and write memory.

**Comment by akshayapadmanabhan** [comment]
So how to install memoryjs on ubuntu?

**Comment by p410n3** [comment]
> So how to install memoryjs on ubuntu?

You can not

**Comment by Rob--** [comment]
@akshayapadmanabhan This library only uses Windows API function and therefore only works on Windows. In the future I might look into making it cross platform but this would take a lot of time, for now it can only be used on Windows, sorry!
