### ISSUE TITLE
Pointer problem

### ISSUE THREAD

**Issue by Zungam1** [Rob--/memoryjs#47]
I saw in the last reports some issues or more some difficutlies in understanding how to use pointers in memoryjs.
Im also struggling with pointers in memoryjs, so is this framework already dead?

Here the pointer:
[https://imgur.com/3eXW7LL](url)
`
const memoryjs = require('memoryjs');
 let offset_life = 0x01FC50F8;

const memRead = async() => {

    memoryjs.openProcess("SildMerlin_x64Steam.exe", async(error, processObject) => {
        if(error){
            console.log('1ERR:' + error)
            return;
        }else{
            console.log(processObject)
        }

        memoryjs.findModule(processObject.szExeFile, processObject.th32ProcessID, async (error, processModule) => {
            if (error) {
                console.log('2ERR:' + error)
                return;
            } else {
                console.log(processModule)
            }

            let life = memoryjs.readMemory(processObject.handle, (processModule.modBaseAddr + offset_life), 'int');
            console.log(life);
        });

    });
}

memRead();
`

i would really like to know why the pointer cannot be found, btw in CE and C++ its not a problem, please enlight me

**Comment by p410n3** [comment]
According to your screenshot, that is a multi level pointer. You cant just use ONE offset and jump straight to it, you have to go step by step.

For example, from my CSGO project:

```JavaScript
//offsets
const oLocalPlayer = mem.getLocalPlayer(csgo.handle, client.szModule); //Get via signature
const oTeamNum = 0xF4; //netvar, stays static usually, even after updates

//Values in memory
localPlayer = mem.readMemory(handle, client + oLocalPlayer, mem.DWORD);
myTeamNum = mem.readMemory(handle, localPlayer + oTeamNum, mem.INT);
```

So you need to follow the first pointer. poiting to a struct in memory. Add an offset to that and follow the next pointer etc. 

Additionally, such long multi level pointers are uncommon, I am sure you can reduce its depth. For a good recent tutorial, watch this: https://www.youtube.com/watch?v=elI6vZR6HGE

**Comment by Zungam1** [comment]
Thanks, that video was really helpfull
