### ISSUE TITLE
ReadMemory stops working at random

### ISSUE THREAD

**Issue by innosflew** [Rob--/memoryjs#54]
I'm trying to use memory.js to read the in game data, such as location, of Red Dead Redemption 2, to display it in Discord. My only issue is that the same memory addresses stop working at random after a while.

I checked with Cheat Engine to make sure the addresses haven't changed between gaming sessions and from what I've seen they haven't. The addresses I use still display the same values.
Memory.js gives me the following error:
```
TypeError: unable to read string (no null-terminator found after 1 million chars)
    at Object.readMemory (C:\bots\node_modules\memoryjs\index.js:104:23)
    at test (C:\bots\index.js:42:32)
```
At line 42 in my code is the ReadMemory function:
`memoryjs.readMemory(handle, address, memoryjs.STRING)`

**Comment by Rob--** [comment]
What does the memory at that address look like in Cheat Engine? In the hex display is there a null terminator after the name of the location?

**Comment by innosflew** [comment]
The memory address is `7FF60D7CE4F8` and this is what it looks like in Memory Viewer in Cheat Engine:
![image](https://user-images.githubusercontent.com/18039193/73023637-424c4800-3e2c-11ea-99c8-240e622c256c.png)

**Comment by Rob--** [comment]
Can you show me the next line of memory too?

**Comment by innosflew** [comment]
The memory address is `7FF60D7CE4F8` and this is what it looks like in Memory Viewer in Cheat Engine:
![image](https://user-images.githubusercontent.com/18039193/73023779-83dcf300-3e2c-11ea-83a6-f8c5dbdf0100.png)

**Comment by innosflew** [comment]
Here is a bigger pic of it:
![image](https://user-images.githubusercontent.com/18039193/73024070-19788280-3e2d-11ea-9140-0565b620a1ca.png)

**Comment by Rob--** [comment]
Replace all the code from [L440](https://github.com/Rob--/memoryjs/blob/master/lib/memoryjs.cc#L440) to [L473](https://github.com/Rob--/memoryjs/blob/master/lib/memoryjs.cc#L440) with this:

```c++
char value[1000000];
ReadProcessMemory(handle, (LPVOID) address, value, 1000000, NULL);
if (args.Length() == 4) argv[1] = String::NewFromUtf8(isolate, str.c_str());
else args.GetReturnValue().Set(String::NewFromUtf8(isolate, str.c_str()));
```

Recompile, and see if that works?

Essentially what it's doing right now is reading 1 character at a time continuously until it finds a null terminator (but this is probably a terrible method), and the 4 lines of code above just try to read 1 million chars at once, but it should include a null terminator. So try that and see if it helps?

**Comment by innosflew** [comment]
I'm not very well versed in C++ but I modified the file with your suggestion and tried to compile it and it gave me this error:
![image](https://user-images.githubusercontent.com/18039193/73026475-c48b3b00-3e31-11ea-8e93-e76a3b5600f2.png)

**Comment by Rob--** [comment]
You aren't compiling it correctly, in the module directory run `npm run build32` or `npm run build64`.

**Comment by innosflew** [comment]
Oh sorry, I feel a bit stupid now 😅

But anyways, I modified the file like this:
![image](https://user-images.githubusercontent.com/18039193/73373940-b027c200-42b9-11ea-87c6-90aab72f2ca4.png)

Then I tried compiling it but it gave me an error:
![image](https://user-images.githubusercontent.com/18039193/73374014-cc2b6380-42b9-11ea-9568-18ec9aedf72d.png)

**Comment by innosflew** [comment]
Oh sorry, I feel stupid now 😅

But anyways, I replaced the code like this:
![image](https://user-images.githubusercontent.com/18039193/73378208-8625ce00-42c0-11ea-950e-4c289bd9b712.png)

And I tried to compile, but I got an error:
![image](https://user-images.githubusercontent.com/18039193/73378251-9a69cb00-42c0-11ea-868f-99c2e0538c76.png)

**Comment by Rob--** [comment]
Oops it's because the code I gave you was wrong, sorry it's because I just typed it out without testing:

```cpp
char value[1000000];
ReadProcessMemory(handle, (LPVOID) address, value, 1000000, NULL);
if (args.Length() == 4) argv[1] = String::NewFromUtf8(isolate, value);
else args.GetReturnValue().Set(String::NewFromUtf8(isolate, value));
```

That should hopefully work!

**Comment by Rob--** [comment]
I've since updated the reading/writing of strings, closing the issue for now.
