### ISSUE TITLE
haveing a hard time geting it to compile

### ISSUE THREAD

**Issue by TheUnChosenOne** [Rob--/memoryjs#57]
> memoryjs@3.2.3 install C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs
> node-gyp rebuild

C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs\build\memoryj
s.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.p
rops" was not found. Confirm that the path in the <Import> declaration is correc 
t, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
ne is installed. You must install peer dependencies yourself.
npm WARN debugmenu@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memoryjs@3.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memoryjs@3.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TheUnChosenOne\AppData\Roaming\npm-cache\_logs\2020-03-15T18_25_34_195Z-debug.log
PS C:\Users\TheUnChosenOne\Desktop\DreamDebuger> npm install memoryjs

> memoryjs@3.2.3 install C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs
> node-gyp rebuild

C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs\build\memoryj
s.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.p
rops" was not found. Confirm that the path in the <Import> declaration is correc 
t, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs  
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN rollback Rolling back doctrine@1.5.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\eslint-plugin-import\node_modules'
ne is installed. You must install peer dependencies yourself.
npm WARN debugmenu@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memoryjs@3.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memoryjs@3.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TheUnChosenOne\AppData\Roaming\npm-cache\_logs\2020-03-15T18_26_27_375Z-debug.log
PS C:\Users\TheUnChosenOne\Desktop\DreamDebuger> npm install memoryjs

> memoryjs@3.2.3 install C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs
> node-gyp rebuild

C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs\build\memoryj
s.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.p
rops" was not found. Confirm that the path in the <Import> declaration is correc 
t, and that the file exists on disk.
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\TheUnChosenOne\Desktop\DreamDebuger\node_modules\memoryjs
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN eslint-config-airbnb-base@12.1.0 requires a peer of eslint@^4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN debugmenu@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memoryjs@3.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the memoryjs@3.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

dont know what i am doing worng

**Comment by cychreus** [comment]
Downgrade Node to v11.15.0
