### ISSUE TITLE
memory read

### ISSUE THREAD

**Issue by dawidpstrak** [Rob--/memoryjs#61]
Hello can you explain how to read memory ? I ve an adress and i know this value from this adress and value is always integer but function returning always 0. Here is my code. 
```
const memoryjs = require('memoryjs');
const processObject = memoryjs.openProcess('client_ogl.exe');
console.log(processObject);

const manaValue = memoryjs.readMemory(processObject, '15562EE4', 'int');
console.log('mana ' + manaValue);
```

**Comment by Rob--** [comment]
Pass through the memory address as a number, not a string:

`const manaValue = memoryjs.readMemory(processObject, 0x15562EE4, 'int');`

**Comment by dawidpstrak** [comment]
It is working. Thank you :). Using this oportunity i would like to pass some feedback about your project. It is nice and i didnt found library like this on web but it is very hard to setup. I spent like 2 days to make it working (but not 100% for now i'm able to use your library by node filename.js and cant setup it to electron and cant run this in browser environment). Would be nice if you make this library easier to setup.

**Comment by Rob--** [comment]
Thanks for the feedback! This library is definitely in need of an upgrade, either to the latest version of Node solely or through backwards compatability with NAN. There is a pull request to update the library that I need to look at. Some time in the future I'll spend some time ensuring it works with the latest version of node and adding new features, but in the meantime have you taken a look at [this tutorial for Node Webkit and Electron](https://github.com/Rob--/memoryjs/wiki/Node-Webkit-&-Electron) that may help you?

**Comment by dawidpstrak** [comment]
Yes i tried this and much more :D. In my case it seems to be problem with packages compatibility. Error says about problem with node compatibility. I tried few version of node but some people fixed it with electron-rebuild package and ill focus on it in next try.

**Comment by Rob--** [comment]
If you could provide some more information on exactly what problems you encountered it would help me in the future, like perhaps screenshots of the errors you encountered. I can imagine most of the problems could be solved by simply updating the library to be compatible with the latest versions of Node however.

You could try forking this repo and merging [this pull request that supposedly upgrades the library to Node 12/13 compatability](https://github.com/Rob--/memoryjs/pull/53) and see if this solves your problems?

**Comment by dawidpstrak** [comment]
Sure it is no problem. Ill try this pull request and I post any issus on github :)
