### ISSUE TITLE
Usage in browser environment

### ISSUE THREAD

**Issue by dawidpstrak** [Rob--/memoryjs#62]
So i succesfully compiled memoryjs in node environment, but i would like to use it in browser enviro mnent and i get this error:
https://pasteboard.co/J5O0LRB.png

It seems to be problem with that thing browser didn't support `require()` import. I tried bundle file with browserify but it didnt works also tried requireJS but same result or i'm doing something wrong.

**Comment by Rob--** [comment]
What do you mean by browser environment? Are you talking about Electron/Webkit?

**Comment by dawidpstrak** [comment]
By running in browser environment i mean i display html file in browser with pinned javascript script. By running in node environment i mean i run script by "node script.js" from CLI so its javascript out of browser environment. By running in Electron i think its out of browser environment i think electron imitate browser environment but im very newbie in out of browser javascript so i dont want to be smart. All i did in javascript it was browser environment.

**Comment by Rob--** [comment]
It's not possible to use this library in a browser environment. You can only use it in a Node environment, or with Electron/Webkit as a "browser".

**Comment by dawidpstrak** [comment]
Sure i just tried because i couldnt setup it to Electron and nw.js, i posted an issue about it too
