### ISSUE TITLE
Electron issue

### ISSUE THREAD

**Issue by dawidpstrak** [Rob--/memoryjs#63]
While I am trying to run memoryjs in electron i get this error.
https://pasteboard.co/J5O7ZC3.png

**Comment by Rob--** [comment]
You need to rebuild the module manually. As the error message states, it was compiled with a version of Node different to the one you are currently using. The module is supposed to rebuild itself upon install, but to do it manually head to the install directory for `memoryjs` and run either `npm run build32` or `npm run build64` depending on whether you are targetting 32 bit or 64 bit architecture.

**Comment by dawidpstrak** [comment]
Unfortunelly it didnt worked for me.
After `npm run build32` error look like : 
[error screen](https://pasteboard.co/J5Yztw9.png)
and after `npm run build64` i got this error : 
[error screen2](https://pasteboard.co/J5YB5Vk.png)

**Comment by Rob--** [comment]
For some reason it is still saying the version of Node it was compiled with is not the same version of Node that you are running. Either try rebuilding and ensuring it rebuilds successfully, or downgrade your version of Node.

**Comment by dw1284** [comment]
I am having the same issue. Can you recommend which Node version to downgrade to that will allow both electron and memoryjs to work together?

**Comment by vladL2C** [comment]
I was having similar issues with latest version of electron it comes packaged with their own node version, i downgraded to `4.2.12` and used `electron-rebuild` to rebuild the packages for electron it seems to be working fine now.

**Comment by Rob--** [comment]
Closing, please comment if there are still issues related to this.

Also worth noting that you will need to use a Node.js architecture equivalent to the platform of your target process (e.g. 32 bit Node for 32 bit target process).
