### ISSUE TITLE
MemoryJS can't get modules

### ISSUE THREAD

**Issue by TwinkerMan** [Rob--/memoryjs#7]
MemoryJS can't find engine.dll or client.dll

All modules:
csgo.exe
ntdll.dll
wow64.dll
wow64win.dll
wow64cpu.dll

P.s even if I use example.js

**Comment by Rob--** [comment]
In your root directory, open the terminal and write `npm run build32` as CSGO is a 32 bit application. If you want to target a 64 bit application run `npm run build64`.

**Comment by TwinkerMan** [comment]
Hm.. Module that I was build using npm run build32 I can't use on my 64bit system. I'm getting Error: %1 is not a valid Win32 application.

**Comment by TwinkerMan** [comment]
I want to include this library into Electron app but it compiles at 64bit. Now I'm understood my mistake, I will try to fix it now. Thanks

**Comment by Rob--** [comment]
No problem. You reminded me of the reason I made this library. I wanted to be able to create a Node Webkit app that "interacts" with CSGO. Reading from and writing to memory is quite slow though.
