### ISSUE TITLE
Does this work on Linux? (specifically Arch Linux)

### ISSUE THREAD

**Issue by UE2020** [Rob--/memoryjs#70]
title

**Comment by Rob--** [comment]
No, this module only uses the Windows API so it's only compatible with Windows OS. We can add support in the future for Arch Linux though.

**Comment by mavit** [comment]
At https://github.com/zbanks/memoryjs there's a fork that partially implements this.  Lets hope that this fork can be reintegrated.

**Comment by Rob--** [comment]
Closing for now. At some point though we could have a Linux implementation alongside the Windows implementation, and just throw errors for methods not yet implemented on the Linux source.
