### ISSUE TITLE
Installation fails with npm and succeeds using git+https

### ISSUE THREAD

**Issue by folkvir** [Rob--/memoryjs#72]
Everything is in the title.

**Fail** using: `npm install memoryjs`
**Succeeds** using `npm install git+https://github.com/Rob--/memoryjs`
**Node version** `v14.15.1` fresh install

Too many logs to be reported here but reproductible.

Perhaps, a new release is needed?

**Comment by Rob--** [comment]
Just published a new release to NPM ([3.4.0](https://www.npmjs.com/package/memoryjs)) that includes @bumpmann's [changes](https://github.com/Rob--/memoryjs/pull/68)!
Thanks again for the contribution @bumpmann!
