### ISSUE TITLE
i am getting a huge error when i am trying to install memoryjs

### ISSUE THREAD

**Issue by srmdev** [Rob--/memoryjs#77]
so i tried to install memoryjs but it is giving me a huge error , I am new to node so i don't know how to fix this issue pls help 
https://pastebin.com/z32aSac2

**Comment by srmdev** [comment]
i found a fix for this issue it seams that only --g did not work for me `npm install --global --production windows-build-tools`

**Comment by jerbear2008** [comment]
This does not appear to work for me, Visual Studio Build Tools never gets installed.
