### ISSUE TITLE
Install error: The build tools for v141 (Platform Toolset = 'v141') cannot be found.

### ISSUE THREAD

**Issue by jerbear2008** [Rob--/memoryjs#81]
I am having the same issue as in #77, and his fix does not work. When running the suggested command, I get the same error as [windows-build-tools/208](https://github.com/felixrieseberg/windows-build-tools/issues/208), and nothing gets installed.
This is the main error:
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build t
ools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install v141 bui
ld tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-cli
ck the solution, and then selecting "Retarget solution". [D:\node\Among Us\node_modules\memoryjs\build\memoryjs.vcxproj
]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
```
[Full log](https://gist.githubusercontent.com/jerbear2008/8d38f15865a87fadd51a0e76fac11ec6/raw/memoryjs-log.txt)

These are the Visual Studio and C++ programs I have installed:
![image](https://user-images.githubusercontent.com/38813665/114599489-06c3b680-9c48-11eb-9425-034dcbdde453.png)

If it helps, I am trying to use CantRunRiver/Ponyo's [among.js package](https://www.npmjs.com/package/among.js) (not among-js, which I am considering switching to). He had a repo for it, but it was recently deleted. I had forked it and added the actual code to it however, at [jerbear2008/among.js](https://github.com/jerbear2008/among.js).

**Comment by jerbear2008** [comment]
Actually, this appears to be a node-gyp error.

**Comment by jerbear2008** [comment]
I have a workaround by copying the folder from another project where this compiled and installed successfully to my node-modules folder, and it works.
[memoryjs.zip](https://github.com/Rob--/memoryjs/files/6306891/memoryjs.zip)

**Comment by Rob--** [comment]
Closing as it seems unrelated to the project, thanks for commenting your solution
