### ISSUE TITLE
Support Node >=14

### ISSUE THREAD

**Issue by takoyaro** [Rob--/memoryjs#85]
Currently can't install this package. Following `npm install memoryjs` you are presented with this error:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for concentrate@0.2.3: wanted: {"node":"~0.10.0"} (current: {"node":"14.15.4","npm":"6.14.10"})
npm ERR! notsup Not compatible with your version of node/npm: concentrate@0.2.3
npm ERR! notsup Not compatible with your version of node/npm: concentrate@0.2.3
npm ERR! notsup Required: {"node":"~0.10.0"}
npm ERR! notsup Actual:   {"npm":"6.14.10","node":"14.15.4"}
```

**Comment by Rob--** [comment]
`concentrate` is complaining here. It was just a helper library to assist with reading/writing buffers.

In 9a0d4fb `concentrate` and `dissolve` were removed.

In 7608be9 `structron` is used in the [new example](https://github.com/Rob--/memoryjs/blob/master/examples/buffers.js) to read/write buffers, but is not installed with the library as a dependency.
