### ISSUE TITLE
Unable to read memory address bigger than 0xFFFFFFFF

### ISSUE THREAD

**Issue by Mystraht** [Rob--/memoryjs#9]
Hello,

I built memoryjs with npm run build64 but when i try to read memory with address that is bigger than 0xFFFFFFFF, it read wrong address.

For example, if i try to read address 0x141EA3612, it will return value of address 0x41EA3612 instead of 0x141EA3612 one.

My attached process is built with a 64bit architecture.

Do you have some idea to fix this ? Thanks

**Comment by Mystraht** [comment]
I found why bug happen.

In memory.h, the type of the second parameter is DWORD instead of DWORD64.
It's why we cant pass number that is bigger than 32bits uint maximum value.

I fix it by replacing DWORD to DWORD64.

But we have another problem, in memoryjs.cc line 348, we get function argument with `args[0]->Uint32Value()` method, this break number that is bigger than 4294967295.

I'm not native C programmer so i quickfix that by adding 4294967296 to `args[0]->Uint32Value()`

    int result = Memory.readMemory<int>(process::hProcess, 4294967296 + args[0]->Uint32Value());

**Comment by LiamKarlMitchell** [comment]
Hmm, should probably be using DWORD_PTR or was it LPVOID ? and have a way to transmit this to the native.

```js
Number.MAX_SAFE_INTEGER.toString(16)
"1fffffffffffff"
```
So that could be a problem.

```js
console.log(0xFFFFFFFF < Number.MAX_SAFE_INTEGER ? 'Safe' : 'Unsafe')
```
Safe

A way around this might be to pass parameters with buffers 
https://community.risingstack.com/using-buffers-node-js-c-plus-plus/

or have the wrapper function pass an extra argument for is x64address then just internally in the native add the amount or subtract the amount.

Or by use of another module?
https://github.com/candu/node-int64-native

ffi gets around it by returning strings as double-precision floating point numbers are imprecise.
https://www.npmjs.com/package/ffi#v8-and-64-bit-types

A solution should also take into consideration that an x64 native module can still use Read Process Memory or Write Process Memory on a x86 process.

Thoughts?

**Comment by karlrobertjanicki** [comment]
I found out that uintptr_t is only part of the answer. [https://github.com/Rob--/memoryjs/pull/14](url)
After changing Uint32Value() to IntegerValue() in readMemory and DWORD to DWORD64 for the base address it was possible to get the correct values in 64 bit programs for pointers as well as for values.

**Comment by karlrobertjanicki** [comment]
You can see the changes in 3792f5d44f465c09ce2d12f098d1eba26ed73fe5

**Comment by Rob--** [comment]
@karlrobertjanicki awesome, it seems as though IntegerValue is the solution for 64 bit integers:

```c
V8EXPORT uint32_t v8::Value::Uint32Value() const;
V8EXPORT int64_t v8::Value::IntegerValue() const;
```

In your fork you don't replace all instances of `Uint32Value()` with `IntegerValue()` though? Any time an address is passed from the Node.js user space to the add-on we should use `IntegerValue()` to access it. I will look into updating the library soon with the relevant fixes.

Thanks!

**Comment by karlrobertjanicki** [comment]
I didn't replace all the instances of Uint32Value() with IntegerValue() because I only used pointer, float and dword. Long story short: because of laziness ;)

**Comment by Rob--** [comment]
@karlrobertjanicki added in 646eb281650ccc14ebf90d645f97934dae384c5d.
Hopefully the library will be much more 64 bit compatible. Soon I will add explicit types such as `int32_t`, `uint32_t` and `int64_t`. Right now, the library's `int` type is simply `int32_t`.

Also, there is no support for getting type `uint64_t` from v8::Value (but there is support for `int64_t`). One solution I've seen for this is getting the double value (`NumberValue()`) and casting it to `uint64_t`.

**Comment by Rob--** [comment]
Closing for now, if there is still problems with 64 bit compatibility I will reopen the issue!

**Comment by karlrobertjanicki** [comment]
Thank you

**Comment by karlrobertjanicki** [comment]
One more thing. I think that the base address is only correct in 64 Bit addresses with:
https://github.com/karlrobertjanicki/memoryjs/blob/3792f5d44f465c09ce2d12f098d1eba26ed73fe5/lib/memoryjs.cc#L107
and
https://github.com/karlrobertjanicki/memoryjs/blob/3792f5d44f465c09ce2d12f098d1eba26ed73fe5/lib/module.cc#L17
DWORD64 did the trick.

**Comment by Rob--** [comment]
@karlrobertjanicki addressed in abc9ee0066cb72e26c51a51e91572cc099d3dbab.

**Comment by karlrobertjanicki** [comment]
Perfect :)

**Comment by karlrobertjanicki** [comment]
I have used memoryjs in a project. You can see the results on youtube
https://www.youtube.com/watch?v=gNiegwbILPg

**Comment by Rob--** [comment]
@karlrobertjanicki Interesting project and awesome video!

**Comment by karlrobertjanicki** [comment]
Thank you. Without memoryjs this would not be possible. Awesome work
