### ISSUE TITLE
Little Endian Support

### ISSUE THREAD

**Issue by ThomasJRyan** [Rob--/memoryjs#91]
I'm not sure if this is even possible given the underlying architecture, but I was wondering if there is any chance of support for little endian reading and writing of memory? I feel like for it to be feasible there would need to be an extra layer written on top to convert the existing big endian memory into little endian

**Comment by Rob--** [comment]
e13970fc2c31bc7b97133607c525cd5fe1fec86b adds support for reading/writing big-endian.

Added the following data types:
- `INT16_BE` - 2 bytes
- `UINT16_BE` - 2 bytes
- `SHORT_BE` - 2 bytes
- `USHORT_BE` - 2 bytes
- `LONG_BE` - 4 bytes
- `ULONG_BE` - 4 bytes
- `INT_BE` - 4 bytes
- `UINT_BE` - 4 bytes
- `INT32_BE` - 4 bytes
- `UINT32_BE` - 4 bytes
- `INT64_BE` - 8 bytes
- `UINT64_BE` - 8 bytes
- `FLOAT_BE` - 4 bytes
- `DOUBLE_BE` - 8 bytes

When one of these types is specified, the library will do one of the following:
- Reading memory: read the appropriate number of bytes as a [buffer](https://nodejs.org/api/buffer.html) and call the appropriate buffer function (e.g. [readInt16BE](https://nodejs.org/api/buffer.html#bufreadint16beoffset))
- Writing memory: create a buffer of appropriate size, call the appropriate buffer function (e.g. [readInt16BE](https://nodejs.org/api/buffer.html#bufreadint16beoffset)) and write the buffer to memory

For `memoryjs.INT64_BE` and `memoryjs.UINT64_BE` types, a [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) needs to be passed or an error will be thrown. At some point I will also require the little endian types (`memoryjs.INT64`, `memoryjs.UINT64`) to be of type BigInt too.

This change probably won't be published to NPM for a while (need to add/overhaul testing), so I'll leave the issue open for a bit and close it if there are no further comments.

**Comment by ThomasJRyan** [comment]
Holy. Did not expect this to actually get addressed. Huge thanks Rob!

**Comment by Rob--** [comment]
No problem @ThomasJRyan , thanks for the feature request!
