### ISSUE TITLE
publish/release newest version to npm? :)

### ISSUE THREAD

**Issue by slauko** [Rob--/memoryjs#93]
hey, could u release the current version to npm ? 
the new readBuffer fixes arent there yet and im tired of recompiling everytime i update or reinstall my other dependencies x'D
otherwise good work ! had no issues with newest version/fixes anymore with memory leaks! 👍

**Comment by Rob--** [comment]
Updated `memoryjs` to version 3.5.1 and released to NPM.

**Comment by slauko** [comment]
> Updated `memoryjs` to version 3.5.1 and released to NPM.

thank u very much!
