### ISSUE TITLE
setProtection is not available in latest version

### ISSUE THREAD

**Issue by xtance** [Rob--/memoryjs#95]
Hello, I've noticed that function called "setProtection" is not available in latest version though it was there around 2019

Will it come back? 
(I'm having an access violation when executing a function, is it protection related error?)
Thanks in advance

**Comment by Rob--** [comment]
`memoryjs.setProtection` has been renamed to `memoryjs.virtualProtectEx`. Refer to the read me, documentation and Wiki for more details :)
